name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.EC2_PORT }}" "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      # Copy only the files needed to build/run (do NOT include config.json)
      - name: Upload app files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: |
            Dockerfile
            requirements.txt
            docker-compose.yml
            scalp.py
            observability/**   # if you kept these (won't be used on AWS path)
          target: /opt/scalper
          overwrite: true
          strip_components: 0

      - name: Build & restart container on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            set -e
            cd /opt/scalper
            # sanity: keep your secrets file in place
            if [ ! -f config.json ]; then
              echo "MISSING /opt/scalper/config.json (put your API keys there)" >&2
              exit 1
            fi
            docker compose down || true
            docker compose build
            docker compose up -d
            docker image prune -f || true
